name: run-tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1, 8.2, 8.3]
        laravel: [11.*, 10.*, 9.*, 8.*]
        dependency-version: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest]
        include:
            - laravel: 11.*
              testbench: 9.*
            - laravel: 10.*
              testbench: 8.*
            - laravel: 9.*
              testbench: 7.*
            - laravel: 8.*
              testbench: 6.*
        exclude:
            - laravel: 11.*
              php: [8.2, 8.1, 8.0]
            - laravel: 10.*
              php: 8.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
